### ISSUE TITLE
Admin Policy Page Loads and Then Goes Blank

### ISSUE THREAD

**Issue by ezrawcdm** [aws-samples/iam-identity-center-team#219]
**Describe the bug**
After successfully logging in as a user that is a member of the TEAM admin Identity Center group, I am trying to set up an eligibility policy. When I click the "Eligibility policy" link, the page loads then goes white. This is a brand new install that has not been configured yet.

**To Reproduce**
1. Log in as a user that is a member of the TEAM admin Identity Center group
2.  the "Eligibility policy" link

**Expected behavior**
The page should allow the user to create an eligibility policy and not disappear.

**Screenshots**
![2024-04-04_12-16-05 (1)](https://github.com/aws-samples/iam-identity-center-team/assets/149620130/de628aa9-8614-4202-bc8a-47b907408bfd)

**Desktop (please complete the following information):**
 - OS: macOS 13.6.3
 - Browser Chrome 
 - 123.0.6312.87 (Official Build) (x86_64)

Was also able to reproduce this on Safari.

**Additional context**
The following errors show in the browser console.

```
Eligible.js:495 TypeError: Cannot read properties of null (reading 'map')
    at Rq (Eligible.js:862:38)
    at aa (react-dom.production.min.js:157:137)
    at Ha (react-dom.production.min.js:180:154)
    at Ks (react-dom.production.min.js:269:343)
    at Ol (react-dom.production.min.js:250:347)
    at Tl (react-dom.production.min.js:250:278)
    at Nl (react-dom.production.min.js:250:138)
    at yl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
po @ react-dom.production.min.js:131
vs @ react-dom.production.min.js:220
Rl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wi @ react-dom.production.min.js:122
Pl @ react-dom.production.min.js:252
yl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wi @ react-dom.production.min.js:122
Ki @ react-dom.production.min.js:123
Gi @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
Oa @ react-dom.production.min.js:170
(anonymous) @ Eligible.js:495
Promise.then (async)
(anonymous) @ Eligible.js:494
Fl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wi @ react-dom.production.min.js:122
Dl @ react-dom.production.min.js:261
yl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wi @ react-dom.production.min.js:122
Ki @ react-dom.production.min.js:123
Gi @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
$t @ react-dom.production.min.js:73
Show 28 more frames
Show less
Eligible.js:862 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'map')
    at Rq (Eligible.js:862:38)
    at aa (react-dom.production.min.js:157:137)
    at Ha (react-dom.production.min.js:180:154)
    at Ks (react-dom.production.min.js:269:343)
    at Ol (react-dom.production.min.js:250:347)
    at Tl (react-dom.production.min.js:250:278)
    at Nl (react-dom.production.min.js:250:138)
    at yl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)

```

**Comment by ezrawcdm** [comment]
In case this is easier to read:

![image](https://github.com/aws-samples/iam-identity-center-team/assets/149620130/f679d08b-661e-4de1-8c42-fbb489d5f898)

**Comment by ezrawcdm** [comment]
Not a defect. The TEAM account needs to be a delegated admin for IAM Identity center. Error handling could be improved by adding a message and troubleshooting steps.
