### ISSUE TITLE
 Unable to log in to TEAM from Amplify's WebUI

### ISSUE THREAD

**Issue by h-ashisan** [aws-samples/iam-identity-center-team#244]
## Trouble

When logging in to TEAM, it hangs indefinitely.
![CleanShot 2024-05-17 at 16 20 04@2x](https://github.com/aws-samples/iam-identity-center-team/assets/90819402/305927d5-ea7b-4805-94f9-883cc856f90c)

The issue #150 has been resolved, but I am concerned that a similar problem is occurring in my environment.

## What I did

I performed the task as follows
https://aws-samples.github.io/iam-identity-center-team/docs/deployment/deployment_process.html

## Erro Logs

The error in CloudWatch Logs for /aws/lambda/teamgetGroups-main is as follows:

```
[ERROR] ParamValidationError: Parameter validation failed:
Invalid type for parameter MemberId.UserId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Traceback (most recent call last):
  File "/var/task/index.py", line 135, in handler
    groupData = list_idc_group_membership(userId)
  File "/var/task/index.py", line 116, in list_idc_group_membership
    for page in paginator:
  File "/opt/python/lib/python3.9/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/opt/python/lib/python3.9/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/opt/python/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.9/site-packages/botocore/client.py", line 919, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/python/lib/python3.9/site-packages/botocore/client.py", line 990, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/python/lib/python3.9/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
```

The error in /aws/appsync/apis/3i23apbkpfgchot7ydrqgohopq is as follows:

```
{
    "logType": "ResponseMapping",
    "path": [
        "getGroups"
    ],
    "fieldName": "getGroups",
    "resolverArn": "arn:aws:appsync:ap-northeast-1:123456789012:apis/3i23apbkpfgchot7ydrqgohopq/types/Query/resolvers/getGroups",
    "functionName": "InvokeTeamgetGroupsLambdaDataSource",
    "requestId": "c2240a6a-7884-496f-b886-3ccdbb0658a9",
    "fieldInError": true,
    "errors": [
        "CustomTemplateException(message=Parameter validation failed:\nInvalid type for parameter MemberId.UserId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>, errorType=Lambda:Unhandled, data=null, errorInfo=null)"
    ],
    "parentType": "Query",
    "graphQLAPIId": "3i23apbkpfgchot7ydrqgohopq",
    "functionArn": "arn:aws:appsync:ap-northeast-1:123456789012:apis/3i23apbkpfgchot7ydrqgohopq/functions/tcye5uqatfch7ffjuc4em2za2a"
}
```

**Comment by tawoyinfa** [comment]
@h-ashisan  is this a new deployment ?

**Comment by h-ashisan** [comment]
@tawoyinfa 
Yes, we are deploying the latest version of the main branch.
